@startuml

package Auth {
    class AuthUser {
        - id: AuthUserId
        - email: Email
        - password: Password
    }
}

package User {
    class User {
        - id: UserId
        - name: UserName
    }


    AuthUser "1" - "1" User
}

package Group {
    class Group {
        - id: GroupId
        - name: GroupName
        - categoryId: GroupCategory
    }

    User "*" -- "1" Group
}

@enduml